language: php

php:
  - 5.3

env:
  - DB=mysql CAKE_VERSION=2.3
  #- DB=pgsql CAKE_VERSION=2.3

before_script:
  - cd .. && git clone git://github.com/cakephp/cakephp && cd cakephp && git checkout $CAKE_VERSION
  - cd .. && ln -s cakephp/lib lib
  - cd wasabi
  - chmod -R 777 tmp
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE wasabi_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE wasabi_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE SCHEMA wasabi_test;' -U postgres -d wasabi_test; fi"
  - set +H
  - echo "<?php
    class DATABASE_CONFIG {
    private \$identities = array(
      'mysql' => array(
        'datasource' => 'Database/Mysql',
        'host' => '0.0.0.0',
        'login' => 'travis'
      ),
      'pgsql' => array(
        'datasource' => 'Database/Postgres',
        'host' => '127.0.0.1',
        'login' => 'postgres',
        'database' => 'wasabi_test',
        'schema' => array(
          'default' => 'public',
          'test' => 'wasabi_test',
        )
      ),
      'sqlite' => array(
        'datasource' => 'Database/Sqlite',
        'database' => array(
          'default' => ':memory:',
          'test' => ':memory:',
        ),
      )
    );
    public \$default = array(
      'persistent' => false,
      'host' => '',
      'login' => '',
      'password' => '',
      'database' => 'wasabi_test',
      'prefix' => ''
    );
    public \$test = array(
      'persistent' => false,
      'host' => '',
      'login' => '',
      'password' => '',
      'database' => 'wasabi_test',
      'prefix' => ''
    );
    public function __construct() {
      \$db = 'mysql';
      if (!empty(\$_SERVER['DB'])) {
        \$db = \$_SERVER['DB'];
      }
      foreach (array('default', 'test') as \$source) {
        \$config = array_merge(\$this->{\$source}, \$this->identities[\$db]);
        if (is_array(\$config['database'])) {
          \$config['database'] = \$config['database'][\$source];
        }
        if (!empty(\$config['schema']) && is_array(\$config['schema'])) {
          \$config['schema'] = \$config['schema'][\$source];
        }
        \$this->{\$source} = \$config;
      }
    }
    }" > Config/database.php
  - cd Config && ln -s security.php.default security.php && cd ..
  - chmod 755 ./Console/cake

script:
  - sh -c "./Console/cake test app AllTests --stderr;"

notifications:
  irc: "irc.freenode.org#wasabi"
  email: false
